language: minimal
dist: xenial
cache:
  apt: true
  directories:
    - riscv

git:
  submodules: false

env:
  - RISCV=$TRAVIS_BUILD_DIR/riscv PATH=$PATH:$RISCV/bin

addons:
  apt:
    packages:
    - autoconf 
    - automake 
    - autotools-dev 
    - bc 
    - bison 
    - build-essential 
    - curl 
    - expat 
    - libexpat-dev 
    - flex 
    - gawk
    - gcc
    - git
    - gperf
    - libgmp-dev
    - libmpc-dev
    - libmpfr-dev 
    - libtool
    - texinfo
    - tmux
    - patchutils
    - zlib1g-dev
    - wget
    - bzip2
    - patch
    - vim-common
    - lbzip2
    - python
    - pkg-config
    - libglib2.0-dev
    - libpixman-1-dev
branches:
  only:
    - dev
    - master

before_install:
  - git submodule init -- riscv-linux
  - git submodule init -- riscv-qemu
  - git clone --shallow-since=2018-05-01 https://github.com/riscv/riscv-linux riscv-linux
  - git clone --shallow-since=2018-05-01 https://github.com/riscv/riscv-qemu riscv-qemu
  - git submodule update --depth=1 -- riscv-linux
  - git submodule update --depth=1 -- riscv-qemu
  - ./fast-setup.sh

jobs:
  include:
    - stage: build everything & test
      script:
        - source ./source.sh
        - travis_wait 120 make
        - travis_wait 10 ./scripts/travis.sh
