language: c

dist: xenial
cache:
  apt: true
  timeout: 1000 #In seconds
  directories:
    - $TRAVIS_BUILD_DIR/riscv

git:
  submodules: false
  depth: 1

env:
  - RISCV=$TRAVIS_BUILD_DIR/riscv
    PATH=$PATH:$RISCV/bin
    KEYSTONE_SDK_DIR=$TRAVIS_BUILD_DIR/keystone-sdk/build
    SDK_MIN_REVISION=$(cat SDK_MIN_REVISION)

addons:
  apt:
    packages:
    - autoconf
    - automake
    - autotools-dev
    - build-essential
    - gcc
    - git

before_install:
  - ./.fast-setup.sh
  - git clone "https://github.com/keystone-enclave/keystone-sdk"
  - pushd keystone-sdk
  - git checkout $SDK_MIN_REVISION
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make install
  - popd

jobs:
  include:
    - stage: clang-format
      if: type = pull_request
      script:
        - FORMAT_COMMIT_START=$(echo $TRAVIS_COMMIT_RANGE | cut -d. -f1)
        - echo "Formatting from $FORMAT_COMMIT_START"
        - git clang-format --diff $FORMAT_COMMIT_START | tee .format-diff
        - \[ "$(cat .format-diff)" = "no modified files to format" \]
    - stage: default build
      script:
        - ./build.sh 
    - stage: USE_FREEMEM
      script:
        - ./build.sh freemem
    - stage: USE_PAGING
      script:
        - ./build.sh paging
